In [1]:
!pip install pymongo

Requirement already satisfied: pymongo in c:\users\navya\anaconda3\lib\site-packages (4.16.0)
Requirement already satisfied: dnspython<3.0.0,>=2.6.1 in c:\users\navya\anaconda3\lib\site-packages (from pymongo) (2.8.0)

In [2]:
from pymongo import MongoClient
import pandas as pd

In [3]:
# put your mongoDB connection link
Connection_String = "mongodb+srv://madnav:Heythere001!@swiftpark-ai-dev.flayktl.mongodb.net/?appName=swiftPark-ai-dev"

In [4]:

# create a connection using Mongo Client
client = MongoClient(Connection_String)

c:\Users\navya\anaconda3\Lib\site-packages\pymongo\pyopenssl_context.py:348: CryptographyDeprecationWarning: Parsed a serial number which wasn't positive (i.e., it was negative or zero), which is disallowed by RFC 5280. Loading this certificate will cause an exception in a future release of cryptography.
  _crypto.X509.from_cryptography(x509.load_der_x509_certificate(cert))

In [5]:
# access the database
db = client['test']
collection = db['parkinglogs']

# 2. Fetch all logs and convert to a list 
logs = list(collection.find())

In [6]:
df = pd.DataFrame(logs)
df

                           _id  spotId  occupied               timestamp  __v
0     69723e91ab85885cf6383eca       1      True 2026-01-22 15:13:21.855    0
1     697548a4c78b176a6eefb246       1      True 2026-01-24 22:33:08.110    0
2     697548bfc78b176a6eefb252       1      True 2026-01-24 22:33:35.289    0
3     697548c3c78b176a6eefb255       1     False 2026-01-24 22:33:39.978    0
4     697548e6c78b176a6eefb263       1     False 2026-01-24 22:34:14.285    0
...                        ...     ...       ...                     ...  ...
1078  6987bb1d5088dd9669a38fdf      28     False 2026-02-07 22:22:21.822    0
1079  6987bb255088dd9669a38fe2      27      True 2026-02-07 22:22:29.003    0
1080  6987bb2c5088dd9669a38fe5      28      True 2026-02-07 22:22:36.261    0
1081  6987bb335088dd9669a38fe9      25      True 2026-02-07 22:22:43.415    0
1082  6987bb3a5088dd9669a38fec       2      True 2026-02-07 22:22:50.596    0

[1083 rows x 5 columns]

In [7]:
# cleaning the data process
df.isnull().sum()  
# So no null values

_id          0
spotId       0
occupied     0
timestamp    0
__v          0
dtype: int64

In [8]:
df.duplicated().sum()
# so there is no duplicate values

np.int64(0)

In [9]:
df.describe()
df.info

<bound method DataFrame.info of                            _id  spotId  occupied               timestamp  __v
0     69723e91ab85885cf6383eca       1      True 2026-01-22 15:13:21.855    0
1     697548a4c78b176a6eefb246       1      True 2026-01-24 22:33:08.110    0
2     697548bfc78b176a6eefb252       1      True 2026-01-24 22:33:35.289    0
3     697548c3c78b176a6eefb255       1     False 2026-01-24 22:33:39.978    0
4     697548e6c78b176a6eefb263       1     False 2026-01-24 22:34:14.285    0
...                        ...     ...       ...                     ...  ...
1078  6987bb1d5088dd9669a38fdf      28     False 2026-02-07 22:22:21.822    0
1079  6987bb255088dd9669a38fe2      27      True 2026-02-07 22:22:29.003    0
1080  6987bb2c5088dd9669a38fe5      28      True 2026-02-07 22:22:36.261    0
1081  6987bb335088dd9669a38fe9      25      True 2026-02-07 22:22:43.415    0
1082  6987bb3a5088dd9669a38fec       2      True 2026-02-07 22:22:50.596    0

[1083 rows x 5 columns]>

In [10]:
# # feature engineering
df2 = df.copy()   # a good practice

# #  we do not need the column named _id and __v so we will remove it
df2.drop(columns=['_id','__v'],inplace=True)

In [11]:
# convert timestamp to date and time format
df2['timestamp'] = pd.to_datetime(df2['timestamp'])
df2

      spotId  occupied               timestamp
0          1      True 2026-01-22 15:13:21.855
1          1      True 2026-01-24 22:33:08.110
2          1      True 2026-01-24 22:33:35.289
3          1     False 2026-01-24 22:33:39.978
4          1     False 2026-01-24 22:34:14.285
...      ...       ...                     ...
1078      28     False 2026-02-07 22:22:21.822
1079      27      True 2026-02-07 22:22:29.003
1080      28      True 2026-02-07 22:22:36.261
1081      25      True 2026-02-07 22:22:43.415
1082       2      True 2026-02-07 22:22:50.596

[1083 rows x 3 columns]

In [12]:
# This returns the min and max timestamp for every spot
spot_timeline = df2.groupby('spotId')['timestamp'].agg(['min', 'max'])
spot_timeline

                           min                     max
spotId
1      2026-01-22 15:13:21.855 2026-02-07 22:19:00.929
2      2026-01-31 20:07:40.437 2026-02-07 22:22:50.596
3      2026-01-31 20:15:35.381 2026-02-07 22:21:09.938
4      2026-01-29 21:54:51.597 2026-02-07 22:13:51.739
5      2026-01-31 20:09:21.420 2026-02-07 22:20:48.429
6      2026-01-31 20:08:23.479 2026-02-07 22:20:26.913
7      2026-01-31 20:21:26.820 2026-02-07 22:20:05.426
8      2026-01-31 20:08:59.964 2026-02-07 22:20:12.576
9      2026-01-31 20:08:09.118 2026-02-07 22:17:49.112
10     2026-01-31 20:11:37.716 2026-02-07 22:20:19.735
11     2026-01-31 20:07:33.288 2026-02-07 22:22:07.446
12     2026-01-31 20:10:54.680 2026-02-07 22:21:31.439
13     2026-01-31 20:14:16.447 2026-02-07 22:14:56.453
14     2026-01-31 20:07:47.564 2026-02-07 22:22:00.284
15     2026-01-31 20:08:16.252 2026-02-07 22:14:06.123
16     2026-01-31 20:10:04.499 2026-02-07 22:17:34.609
17     2026-01-31 20:10:40.359 2026-02-07 22:19:51.065
18     2026-01-29 12:27:13.740 2026-02-07 22:21:24.251
19     2026-01-31 20:08:30.728 2026-02-07 22:18:25.014
20     2026-01-31 20:12:49.502 2026-02-07 22:19:58.226
21     2026-01-29 12:27:01.601 2026-02-07 22:18:53.734
22     2026-01-31 20:07:54.728 2026-02-07 22:20:34.074
23     2026-01-29 21:54:58.758 2026-02-07 22:22:14.644
24     2026-01-31 20:10:33.206 2026-02-07 22:21:45.874
25     2026-01-31 20:08:37.907 2026-02-07 22:22:43.415
26     2026-01-31 20:08:52.219 2026-02-07 22:19:08.089
27     2026-01-31 20:10:26.036 2026-02-07 22:22:29.003
28     2026-01-31 20:09:07.095 2026-02-07 22:22:36.261
29     2026-01-31 20:13:11.112 2026-02-07 22:20:55.601
30     2026-01-29 21:55:05.873 2026-02-07 22:21:53.055

In [13]:
# This calculates the time elapsed between each log entry for that specific spot
df2['time_diff'] = df2.groupby('spotId')['timestamp'].diff()
df2

      spotId  occupied               timestamp              time_diff
0          1      True 2026-01-22 15:13:21.855                    NaT
1          1      True 2026-01-24 22:33:08.110 2 days 07:19:46.255000
2          1      True 2026-01-24 22:33:35.289 0 days 00:00:27.179000
3          1     False 2026-01-24 22:33:39.978 0 days 00:00:04.689000
4          1     False 2026-01-24 22:34:14.285 0 days 00:00:34.307000
...      ...       ...                     ...                    ...
1078      28     False 2026-02-07 22:22:21.822 0 days 00:03:49.591000
1079      27      True 2026-02-07 22:22:29.003 0 days 00:01:47.752000
1080      28      True 2026-02-07 22:22:36.261 0 days 00:00:14.439000
1081      25      True 2026-02-07 22:22:43.415 0 days 00:01:26.321000
1082       2      True 2026-02-07 22:22:50.596 0 days 00:17:58.384000

[1083 rows x 4 columns]

In [14]:
# the whole dataframe is sorted so history is in order
df2 = df2.sort_values(by=['spotId', 'timestamp'])

# This compares a spot's current status to its OWN previous status
df2['status_change'] = df2.groupby('spotId')['occupied'].diff()

# 3. View the results
print(df2[['spotId', 'timestamp', 'occupied', 'status_change']].head(20))

     spotId               timestamp  occupied status_change
0         1 2026-01-22 15:13:21.855      True           NaN
1         1 2026-01-24 22:33:08.110      True             0
2         1 2026-01-24 22:33:35.289      True             0
3         1 2026-01-24 22:33:39.978     False            -1
4         1 2026-01-24 22:34:14.285     False             0
5         1 2026-01-24 22:34:21.688      True             1
41        1 2026-01-31 20:11:08.944      True             0
91        1 2026-01-31 20:17:08.588      True             0
95        1 2026-01-31 20:17:37.267     False            -1
98        1 2026-01-31 20:17:58.864      True             1
109       1 2026-01-31 20:19:17.671     False            -1
125       1 2026-01-31 20:21:12.498      True             1
139       1 2026-02-07 17:08:29.304      True             0
172       1 2026-02-07 17:12:21.579      True             0
313       1 2026-02-07 17:29:15.349     False            -1
316       1 2026-02-07 17:29:36.927     False             0
317       1 2026-02-07 17:29:44.108      True             1
388       1 2026-02-07 17:38:15.501      True             0
447       1 2026-02-07 17:45:20.778     False            -1
538       1 2026-02-07 17:56:16.642     False             0

In [15]:
# count the turovers for each spot
turnover_counts = df2[df2['status_change']==1].groupby('spotId')['time_diff'].size()
turnover_counts

spotId
1      7
2      9
3      7
4      8
5     10
6      9
7      8
8      7
9      8
10     5
11    10
12    13
13    10
14     8
15     9
16     6
17    11
18     9
19     8
20    10
21     6
22     9
23     4
24     7
25     4
26    14
27     9
28    11
29    11
30    10
Name: time_diff, dtype: int64

In [16]:
# this calculates the total occupancy time
time_duration = df2[df2['occupied']==True].groupby('spotId')['time_diff'].sum()
time_duration

spotId
1    16 days 02:22:36.258000
2     0 days 04:22:54.617000
3     7 days 00:57:05.399000
4     7 days 00:47:15.949000
5     7 days 00:57:34.404000
6     7 days 01:08:34.245000
7     0 days 04:04:49.259000
8     0 days 00:42:58.045000
9     0 days 04:43:47.217000
10    0 days 00:40:05.179000
11    6 days 21:55:18.806000
12    7 days 00:57:55.276000
13    0 days 04:08:28.404000
14    0 days 04:05:15.833000
15    6 days 21:50:15.127000
16    6 days 21:50:44.259000
17    6 days 21:59:59.215000
18    2 days 11:59:35.640000
19    6 days 21:51:28.442000
20    0 days 00:50:43.431000
21    2 days 08:26:50.503000
22    6 days 21:40:32.268000
23    0 days 04:10:22.155000
24    0 days 04:35:14.332000
25    0 days 01:08:23.852000
26    6 days 21:47:57.500000
27    0 days 01:11:31.523000
28    7 days 01:15:25.462000
29    0 days 04:21:42.856000
30    0 days 00:58:32.952000
Name: time_diff, dtype: timedelta64[ns]

In [17]:
# this will calculate which hours are peak
df2['hour']=df2['timestamp'].dt.hour

peak_hours = df2.groupby('hour')['occupied'].mean()
peak_hours

hour
12    1.000000
15    1.000000
17    0.473923
18    0.509728
20    0.466102
21    0.470588
22    0.433673
Name: occupied, dtype: float64

In [18]:
# lets count the average hour per spot

avg_hour_per_spot = df2[df2['occupied']==True].groupby('spotId')['hour'].mean()
avg_hour_per_spot

spotId
1     18.812500
2     18.384615
3     18.500000
4     19.000000
5     18.500000
6     18.000000
7     18.230769
8     18.818182
9     18.500000
10    19.250000
11    18.250000
12    18.304348
13    18.307692
14    19.000000
15    18.600000
16    18.684211
17    18.217391
18    18.411765
19    18.705882
20    19.000000
21    18.352941
22    18.565217
23    19.888889
24    18.842105
25    18.900000
26    18.375000
27    18.800000
28    18.450000
29    19.350000
30    18.764706
Name: hour, dtype: float64

In [19]:
# 1. Start with a list of all 30 spot IDs to ensure no one is left out
master_df = pd.DataFrame({'spotId': range(1, 31)}).set_index('spotId')

# 2. Join your features
master_df['turnover'] = turnover_counts
master_df['total_time'] = time_duration
master_df['avg_hour'] = avg_hour_per_spot

# 3. Fill NaN with 0 (Crucial for the ML model!)
master_df = master_df.fillna(0)

In [20]:
master_df.to_csv('master_data.csv',index=False)

In [21]:
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

In [22]:
df_master = pd.read_csv(r'master_data.csv')

In [23]:
# Convert the Timedelta string/object into a float (total minutes)
df_master['total_time'] = pd.to_timedelta(df_master['total_time']).dt.total_seconds() / 60


features = ['turnover','total_time','avg_hour']
X= df_master[features]

In [24]:
# Scaling (The "Fairness" Step)
# This ensures 'total_time' doesn't dominate 'turnover' due to larger numbers
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [25]:
kmeans = KMeans(n_clusters=3,random_state=42,n_init=10)
df_master['cluster'] = kmeans.fit_predict(X_scaled)

c:\Users\navya\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

In [26]:
# Calculate the average values for each cluster
cluster_analysis = df_master.groupby('cluster')[['turnover', 'total_time', 'avg_hour']].mean()
print("--- Cluster Profiles ---")
print(cluster_analysis)

--- Cluster Profiles ---
         turnover    total_time   avg_hour
cluster
0        4.333333    119.617700  19.346296
1        9.428571  10977.336440  18.497468
2        8.615385    694.800785  18.674060

In [27]:
cluster_names = {
    0: "Prime Shopping Zone",
    1: "Inactive Zone",
    2: "Long-Stay Zone"
}

df_master['zone_name']= df_master['cluster'].map(cluster_names)

In [30]:
import pandas as pd

# 1. Map your specific zone names to real Square One anchor points
# These coordinates place the spots in actual parking lots instead of the mall interior
zone_coords = {
    'Prime Shopping Zone': [43.5947, -79.6438],  # North Lot (P1)
    'Inactive Zone': [43.5938, -79.6465],        # West Lot (P3)
    'Long-Stay Zone': [43.5910, -79.6415]        # South Lot (P7)
}

def assign_coords(row):
    # Get the anchor based on the zone_name column
    anchor = zone_coords.get(row['zone_name'], [43.5930, -79.6425])
    
    # We use the spotId to create a row effect so they don't overlap
    # This prevents the "straight line" look by adding a small diagonal offset
    index_offset = int(row['spotId']) % 10 
    lat_jitter = index_offset * 0.00005
    lng_jitter = index_offset * 0.0001
    
    return pd.Series([anchor[0] + lat_jitter, anchor[1] + lng_jitter])

# 2. Update the columns in your existing master_df
master_df[['lat', 'lng']] = master_df.apply(assign_coords, axis=1)


print("✅ Coordinates updated to real Square One parking lots!")

KeyError: 'zone_name'

In [ ]:
# If 'spotId' was missing, we recreate it based on the number of rows
# This ensures every spot has a unique ID from 1 to 30

df_master['spotId'] = range(1, len(df_master)+1)

df_master.to_csv('final_clustered_data.csv', index=False)